"""add_cascade_deletes

Revision ID: 12ba65011f24
Revises: 65a1f25b2e85
Create Date: 2025-12-29 14:11:10.277652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ba65011f24'
down_revision: Union[str, Sequence[str], None] = '65a1f25b2e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_user_id_fkey'), 'activity', type_='foreignkey')
    op.create_foreign_key(None, 'activity', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('application_job_id_fkey'), 'application', type_='foreignkey')
    op.drop_constraint(op.f('application_user_id_fkey'), 'application', type_='foreignkey')
    op.drop_constraint(op.f('application_resume_id_fkey'), 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'resume', ['resume_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'application', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('deadline_user_id_fkey'), 'deadline', type_='foreignkey')
    op.drop_constraint(op.f('deadline_application_id_fkey'), 'deadline', type_='foreignkey')
    op.create_foreign_key(None, 'deadline', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deadline', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interview_user_id_fkey'), 'interview', type_='foreignkey')
    op.drop_constraint(op.f('interview_application_id_fkey'), 'interview', type_='foreignkey')
    op.create_foreign_key(None, 'interview', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interview', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_user_id_fkey'), 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('offer_user_id_fkey'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('offer_application_id_fkey'), 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'offer', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resume_user_id_fkey'), 'resume', type_='foreignkey')
    op.create_foreign_key(None, 'resume', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.create_foreign_key(op.f('resume_user_id_fkey'), 'resume', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key(op.f('offer_application_id_fkey'), 'offer', 'application', ['application_id'], ['id'])
    op.create_foreign_key(op.f('offer_user_id_fkey'), 'offer', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key(op.f('job_user_id_fkey'), 'job', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.create_foreign_key(op.f('interview_application_id_fkey'), 'interview', 'application', ['application_id'], ['id'])
    op.create_foreign_key(op.f('interview_user_id_fkey'), 'interview', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'deadline', type_='foreignkey')
    op.drop_constraint(None, 'deadline', type_='foreignkey')
    op.create_foreign_key(op.f('deadline_application_id_fkey'), 'deadline', 'application', ['application_id'], ['id'])
    op.create_foreign_key(op.f('deadline_user_id_fkey'), 'deadline', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key(op.f('application_resume_id_fkey'), 'application', 'resume', ['resume_id'], ['id'])
    op.create_foreign_key(op.f('application_user_id_fkey'), 'application', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('application_job_id_fkey'), 'application', 'job', ['job_id'], ['id'])
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.create_foreign_key(op.f('activity_user_id_fkey'), 'activity', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
