"""Updated resume Table

Revision ID: 1c8b9b469516
Revises: 96dc67c4e0c9
Create Date: 2025-12-29 11:43:53.616073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c8b9b469516'
down_revision: Union[str, Sequence[str], None] = '96dc67c4e0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_resume_uploaded_at'), table_name='resume')
    op.create_index(op.f('ix_resume_created_at'), 'resume', ['created_at'], unique=False)
    op.drop_column('resume', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_resume_created_at'), table_name='resume')
    op.create_index(op.f('ix_resume_uploaded_at'), 'resume', ['uploaded_at'], unique=False)
    op.drop_column('resume', 'created_at')
    # ### end Alembic commands ###
