"""sync models

Revision ID: 871af9063ddc
Revises: YOUR_BASE_MIGRATION_ID_HERE  # ⚠️ CRITICAL: REPLACE WITH ACTUAL BASE REVISION ID
Create Date: 2025-12-25 16:06:41.652915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871af9063ddc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with production-ready tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('due_date', sa.DateTime(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('priority', sa.String(length=20), nullable=False),
        sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), onupdate=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='deadline_priority_check'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_application_id'), 'deadline', ['application_id'], unique=False)
    op.create_index(op.f('ix_deadline_completed'), 'deadline', ['completed'], unique=False)
    op.create_index(op.f('ix_deadline_due_date'), 'deadline', ['due_date'], unique=False)
    op.create_index(op.f('ix_deadline_user_id'), 'deadline', ['user_id'], unique=False)
    
    op.create_table('interview',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('time', sa.Time(), nullable=False),  # Proper time type instead of string
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('interviewer', sa.String(length=255), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('prep_checklist', sa.Text(), nullable=True),
        sa.Column('reminders', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), onupdate=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_application_id'), 'interview', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_user_id'), 'interview', ['user_id'], unique=False)
    
    op.create_table('offer',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=False),
        sa.Column('company_name', sa.String(length=255), nullable=False),
        sa.Column('position', sa.String(length=255), nullable=False),
        sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=False),  # Proper money type
        sa.Column('benefits', sa.Text(), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('deadline', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('negotiation_history', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), onupdate=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'negotiating')", name='offer_status_check'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_application_id'), 'offer', ['application_id'], unique=False)
    op.create_index(op.f('ix_offer_status'), 'offer', ['status'], unique=False)
    op.create_index(op.f('ix_offer_user_id'), 'offer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - WARNING: THIS WILL PERMANENTLY DELETE ALL DEADLINE, INTERVIEW, AND OFFER DATA"""
    # ⚠️ SAFETY WARNING: Uncomment below in production to prevent accidental data loss
    # import os
    # if not os.environ.get('FORCE_DOWNGRADE'):
    #     raise RuntimeError(
    #         "DOWNGRADE ABORTED: This would delete critical application data. "
    #         "Set FORCE_DOWNGRADE=1 environment variable to proceed."
    #     )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_user_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_status'), table_name='offer')
    op.drop_index(op.f('ix_offer_application_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_interview_user_id'), table_name='interview')
    op.drop_index(op.f('ix_interview_application_id'), table_name='interview')
    op.drop_table('interview')
    op.drop_index(op.f('ix_deadline_user_id'), table_name='deadline')
    op.drop_index(op.f('ix_deadline_due_date'), table_name='deadline')
    op.drop_index(op.f('ix_deadline_completed'), table_name='deadline')
    op.drop_index(op.f('ix_deadline_application_id'), table_name='deadline')
    op.drop_table('deadline')
    # ### end Alembic commands ###