"""Update the Job to  enable cascadin on deletion

Revision ID: 96dc67c4e0c9
Revises: 537de14e35f2
Create Date: 2025-12-28 01:31:18.987842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dc67c4e0c9'
down_revision: Union[str, Sequence[str], None] = '537de14e35f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
