"""check

Revision ID: bb3c6396b634
Revises: 871af9063ddc
Create Date: 2025-12-25 22:28:15.863656

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3c6396b634'
down_revision: Union[str, Sequence[str], None] = '871af9063ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deadline', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('deadline', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('deadline', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('deadline', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('deadline_user_id_fkey'), 'deadline', type_='foreignkey')
    op.drop_constraint(op.f('deadline_application_id_fkey'), 'deadline', type_='foreignkey')
    op.create_foreign_key(None, 'deadline', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'deadline', 'application', ['application_id'], ['id'])
    op.alter_column('interview', 'time',
               existing_type=postgresql.TIME(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('interview', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('interview', 'prep_checklist',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('interview', 'reminders',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('interview_application_id_fkey'), 'interview', type_='foreignkey')
    op.drop_constraint(op.f('interview_user_id_fkey'), 'interview', type_='foreignkey')
    op.create_foreign_key(None, 'interview', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'interview', 'application', ['application_id'], ['id'])
    op.alter_column('offer', 'salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('offer', 'benefits',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('offer', 'negotiation_history',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('offer', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('offer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('offer_user_id_fkey'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('offer_application_id_fkey'), 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'offer', 'application', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key(op.f('offer_application_id_fkey'), 'offer', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('offer_user_id_fkey'), 'offer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('offer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('offer', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('offer', 'negotiation_history',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('offer', 'benefits',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('offer', 'salary',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.create_foreign_key(op.f('interview_user_id_fkey'), 'interview', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('interview_application_id_fkey'), 'interview', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interview', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('interview', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('interview', 'reminders',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('interview', 'prep_checklist',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('interview', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('interview', 'time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.drop_constraint(None, 'deadline', type_='foreignkey')
    op.drop_constraint(None, 'deadline', type_='foreignkey')
    op.create_foreign_key(op.f('deadline_application_id_fkey'), 'deadline', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('deadline_user_id_fkey'), 'deadline', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('deadline', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('deadline', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('deadline', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('deadline', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
