"""v4 of the models

Revision ID: f683a20f2a76
Revises: 2d1b48d24d09
Create Date: 2025-12-26 12:46:41.779698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f683a20f2a76'
down_revision: Union[str, Sequence[str], None] = '2d1b48d24d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_applied_date'), table_name='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_applied_date'), 'application', ['applied_date'], unique=False)
    # ### end Alembic commands ###
